targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
          include_if_null: false
      injectable_generator:
        options:
          auto_register: true
        enabled: true
      retrofit_generator:
        enabled: true
      freezed:
        enabled: true
    sources:
      - "lib/**"
      - "test/**" 